--CRIANDO UM BANCO DE DADOS
CREATE DATABASE SpMedGroup;

--USANDO O BANCO DE DADOS
USE SpMedGroup;

--CRIADOR AS TABELAS DO SpMedGroup

CREATE TABLE TipoUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE Situacao(
	IdSituacao INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE Especialidade(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(255) NOT NULL UNIQUE	
);
CREATE TABLE Instituicao(
	IdInstituicao INT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(255) NOT NULl,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	HorarioAbertura TIME NOT NULL,
	HorarioFechamento TIME NOT NULL,
	RazaoSocial VARCHAR(255) NOT NULL,
	Endereco VARCHAR(255) NOT NULL
);
CREATE TABLE Medico(
	IdMedico INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	Telefone VARCHAR(50) NOT NULL,
	Endereco VARCHAR(255) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade) NOT NULL
);
CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(255) NOT NULL,
	Telefone VARCHAR(255) NOT NULL,
	DataNascimento DATETIME2 NOT NULL,
	CPF CHAR(14) NOT NULL UNIQUE,
	RG CHAR(9) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(255) NOT NULL,
	Endereco VARCHAR(255) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario)NOT NULL
);
CREATE TABLE Consulta(
	IdConsulta INT PRIMARY KEY IDENTITY,
	Descricao TEXT NOT NULL,
	DataDaConsulta DATETIME2 NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL, 
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico) NOT NULL,
	IdSituacao INT FOREIGN KEY REFERENCES Situacao(IdSituacao) NOT NULL,
	IdInstituicao INT FOREIGN KEY REFERENCES Instituicao(IdInstituicao) NOT NULL
);